# Generated by Django 4.0.4 on 2022-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='afisha',
            name='fess_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='Указать сумму в доллорах', verbose_name='Сборы в США'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='Указать сумму в доллорах', verbose_name='Бюджет'),
        ),
    ]
